"""Add Spotify fields to artist model

Revision ID: 1d2bc2efe8e7
Revises: ca2bb95d843e
Create Date: 2026-01-13 18:45:27.538432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2bc2efe8e7'
down_revision = 'ca2bb95d843e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('spotify_id', sa.String(length=50), nullable=True))
    op.add_column('artists', sa.Column('spotify_image_url', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('spotify_popularity', sa.Float(), nullable=True))
    op.add_column('artists', sa.Column('spotify_followers', sa.Float(), nullable=True))
    op.add_column('artists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'artists', ['spotify_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='unique')  # type: ignore[arg-type]
    op.drop_column('artists', 'updated_at')
    op.drop_column('artists', 'spotify_followers')
    op.drop_column('artists', 'spotify_popularity')
    op.drop_column('artists', 'spotify_image_url')
    op.drop_column('artists', 'spotify_id')
    # ### end Alembic commands ###