"""Add updated_at column to setlists table

Revision ID: ca2bb95d843e
Revises: 79f59b424caa
Create Date: 2026-01-13 15:41:36.824350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2bb95d843e'
down_revision = '79f59b424caa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setlists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setlists', 'updated_at')
    # ### end Alembic commands ###